name: AI Marketing Agent

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Blog Generator
        run: python content_generator.py

      - name: Run LinkedIn Generator
        run: python linkedin_post.py

      - name: Run YouTube Generator
        run: python youtube_description.py
